image:
  repository: '139294524816.dkr.ecr.ap-southeast-2.amazonaws.com/demo-node-app'
  tag: 'staging'
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: alb
  host: demo-node-app-eks.aws.deanlofts.xyz

env:
  APP_ENV: staging
  LOG_LEVEL: info
  PORT: '3000'
  S3_BUCKET: devops-refresher-staging-app-65d854
  DB_HOST: staging-app-postgres.c4msfqd2cnyb.ap-southeast-2.rds.amazonaws.com
  DB_PORT: '5432'
  DB_USER: app_user_staging
  DB_NAME: app_staging
  DB_SSL: required
  REDIS_HOST: master.staging-app-redis.hskbd9.apse2.cache.amazonaws.com
  REDIS_PORT: '6379'
  SELF_TEST_ON_BOOT: 'false'

secrets:
  DB_PASS: ''
  REDIS_PASS: ''

resources: {}
